[강의1 Promise \(then, catch) 로 이동](https://www.youtube.com/watch?v=Sn0ublt7CWM)  
[강의2 Promise 2 - new Promise 로 이동](https://www.youtube.com/watch?v=PasFh_t1mhY)

> 비동기적으로 동작하는 함수들은 프라미스를 이용해서 제어해야 하는 경우가 많습니다. 동기적인 것과 비동기적인 것이 어떤 차이가 있는지, 프라미스로 되어 있는 함수는 어떻게 다뤄야 하는지를 알아보는 수업입니다.
  


본 강의에서는 Promise의 깊은 내용을 다루지는 않는다. 
대신 강의 1에서는 기본적인 Promise 사용법,
강의 2에서는 Promise를 직접 만드는법에 대해 배운다.  
상세한 Promise 


---  
  
# 강의 1 - Promise (then,catch)  
  
## 싱크가 뭔데
JS를 다루다 보면 Synchronous와 Asynchronous를 만나게 된다. 이게 어떤 뜻인지에 대해 먼저 알아보자

## 실험
```
console.log(1);
console.log(2);
console.log(3);
console.log(4);
```
이러면 순서대로 1 2 3 4 가 출력될 것이다   
  
```
console.log(1);
console.log(2);
setTimeout(function(){console.log(3)}, 5000);
console.log(4);
```
이러면 5초 뒤에 3이 실행되니까    
1 2 4 3 이 출력될 것이다  
  
이렇게 따로 처리되는 것을 "비동기적(Asynchronous)이다" 라고 한다.  


## 동기 vs 비동기
![image](https://user-images.githubusercontent.com/101965836/163661441-b197ebc2-aadf-4c54-ab95-f228ad7f6625.png)  
![image](https://user-images.githubusercontent.com/101965836/163661450-f5856a2a-2c1e-49b4-88d5-c977c8c66dfb.png)  

## 언제 비동기 처리를 쓰느냐?
대표적으로 통신에서 쓰인다. 통신이 언제 끝날지 모르니까.  
파일 수신을 예로 A.jpg 라는 파일을 요청한다고 해보자.  
서버에 먼저 A.jpg라는 파일을 요청해야 할 것이다. 그러면 서버가 A.jpg를 찾는 동안 클라이언트는 응답만 기다리기 보다는 다른 처리를 해야 합리적일 것이다. 근데 서버로부터 A.jpg를 찾았다라는 응답을 받기 전 까지 클라이언트가 계속 응답 대기만 하고 있으면, 굉장히 비효율적인 자원 처리가 될 것이다. 따라서 이러한 부분에서는 비동기적으로 일단 응답 전까지 다른 작업을 하고 있는 것이 맞다.  

## Ajax
브라우저와 웹서버가 페이지 리로드를 하지 않고도 자바스크립트를 이용해서 서로 통신하는 것.  

## 만약 동기적으로 통신했다면?
통신이 이뤄지는 동안 웹 브라우저에 입력(클릭)이 모두 멈춰버릴 것이다.   


## 파일 받아오기 예제로 처음 만나는 promise
[코드출처](https://developer.mozilla.org/ko/docs/Web/API/Fetch_API/Using_Fetch)  
[jsonplaceholder](https://jsonplaceholder.typicode.com/)   

> jsonplaceholder란?  
> 코드를 작성하다 보면 json 같은걸 서버에서 받아오는 코드를 짤 때가 있다. 그런데 당장에 받아올 json 구축 하는 것도 일이기 > 때문에 임시로 json 받아올 때 jsonplaceholder를 사용하면 url을 통해 json을 얻어올 수 있다.  
```js
fetch('https://jsonplaceholder.typicode.com/posts')
  .then(function(response) {
    return response.json();
  })
  .then(function(myJson) {
    console.log(JSON.stringify(myJson));
  });
```
위의 파일 받아오기 예제에서 먼저 fetch를 쓴 것을 볼 수 있다.   
fetch는 해당 URL로 가서 파일 받아오는 명령이다.   
그런데 fetch()의 mdn 문서를 잘 보면 [공식 문서 fetch()](https://developer.mozilla.org/en-US/docs/Web/API/fetch)  
![image](https://user-images.githubusercontent.com/101965836/163663958-e452f54e-a4a1-45cb-a71f-563432fc141e.png)    
이렇게 return이 promise 형식이라고 나와있다.   
그러면 이제 promise에 대해 알아보자  

## promise는 마치 진동벨
우리가 카페에 가서 커피를 시킬 때를 생각해보자. 커피는 주문하자마자 바로 나오는 게 아니다. 조금 기다려야하는데 그 동안 카운터에 죽치고 서있는 것은 아니다. 직원이 진동벨을 주고 진동벨 울리면 찾으로 오라고 하는 카페가 일반적이다.  
  
마찬가지로 promise도 약간은 다르지만 카페의 진동벨 같은 식이다. return으로 바로 커피를 받을 수 없는 상황이 있다. 앞서 본 데이터 요청 처럼 말이다. 이런 경우에는 진동벨 역할의 promise를 준다.  
다만 promise는 좀 더 똑똑한 진동벨이다. promise는 커피가 나오면 어떤 행동을 할 지 지정해주는 .then() 이라는 애가 있다. 마치 로봇처럼, 커피가 나오면 then 안에 들어간 명령을 실행한다. 만약 카페 진동벨이 promise 였다면, .then(커피 갖고와) 라고 할 수도 있겠다. 커피가 나오면 벨만 울리지 말고, 직접 커피도 테이블로 갖고 와주는 똑똑한 진동벨이 promise 인 것이다.  
  
  
## promise의 사용법
다시 promise에 대해 정리해보자.  
promise를 쓰는 이유는? 어떤 return값을 받고 싶지만, 곧바로 그 return값을 받을 순 없고 좀 시간이 걸릴 때. 이럴 때는 비동기적으로 처리해야한다. 그래서 진동벨로 promise를 준다.  
promise를 return으로 받으면 이제 어떻게 해야하나? promise가 성공적으로 수행됐을 경우 할 행동을 정해주면 된다. .then(callback function) 으로 지정해줄 수 있다.  
promise가 실패하면? .then()과 마찬가지로 .catch(callback function)을 추가해주면 된다.   


## 다시 데이터 받아오는 코드를 보자
다시 위 데이터 fetch 코드를 잘 살펴보자. 이제 어느정도 .then이 왜 나왔는지 알 수 있다.   
fetch( ... ).then(...).then(...) 같은 식으로 then then 거렸던 것들. 이게 다 promise가 이어지는 모습이었다는것을 알 수 있다.  
  
  
  
## 비동기와 동기의 시작을 알리는 promise  
  
기본 비동기, 동기 개념은 callback function을 처음 접하면서 자연스럽게 알게 된다.  
setTimeout이라던가 setInterval 함수를 접하면서 비동기 처리에 대해 처음 알게되고, 각종 기본 예제에서도 비동기에 대해 필연적으로 맞닥뜨리게 된다.   
이러한 비동기적 처리에 대해서는 또 다시 promise를 마주치게 된다. 뭐를 return 받고 싶은데 그걸 곧 바로 받을 수 없을 때, 일단 promise를 받아둔다는 것. 입문 수준에서는 이 정도만 알아두자. 
  
>  promise를 리턴 하는 함수는 비동기 함수일 가능성이 높다
>  promise에는 then과 catch를 쓸 수 있다.
>  then은 promise가 성공했을 때, catch는 promise가 실패했을 때.
   

---

# 강의 2 - new Promise

직접 Promise를 만들면서 promise에 대해 알아보자

## Promise 생성해보기 
```js
var job1 = new Promise();
```
이렇게 하면 에러가 난다. 왜냐하면 Promise는 필수적으로 (1)성공했을때 실행 할 것 (2)실패했을때 실행 할 것 이 필요하기 때문이다. 단 이를 각각의 function으로 넘겨주지 않고, 한번에 function으로 넘겨준다. 아래와 같이 말이다.  
  
```js
var job1 = new Promise(function(resolve, reject){});
```
이렇게 하면 Promise 생성 자체에서는 에러가 나지 않는다. 여기서 promise 안에 넘겨준 function의 인자인 resolve와 reject는 각각 성공했을때는 resolve, 실패했을때는 reject를 실행한다는 뜻이다.  
물론 위 코드에서는 뭐가 성공이고 실패인지 정의되어있지 않다. 따라서 job1이라는 Promise에는 .then .catch는 실행되지 못한다.  
  
## Promise 성공했냐 실패했냐? 만들어보기
근데 저 Promise 안에 넣어둔 함수에서, resolve와 reject은 어떻게 쓰는걸까? 이에 대해서 알아보자.  
결론부터 말하자면, 
```js
var job1 = new Promise(
  function(resolve, reject){
    if( ) {
      resolve(리턴할 data); 
    }
    reject(알려줄 err); 
  }
);
```
이렇게 작성하면 된다. 이렇게 하고 아래와 같이 .then 을 쓰면 된다.  
```
job1.then(function(data){
  console.log('data',data);
})
```

## 실제로는 변수에 넣는 식으로 쓰진 않음
```js
function job1(){
  return new Promise(function(resolve, reject){
      if( ) {
        resolve(리턴할 data); 
      }
      reject(알려줄 err); 
    }
  );
}
```
```js
job1().then(function(data){ ... });
```
실제 코드에서는 이런식으로 Promise를 { (1)생성후 할당 (2)동작 } 2가지 작업을 한번에 할 수 있도록 함수로 감싸서 promise를 return하는 식으로 만들어두고 쓴다.   

이렇게 Promise를 생성하는 방법에 대해 간단히 알아봤다. 이제 promise의 이점에 대해 좀 더 알아보자  

## callback 지옥
```js
//Callback HELL
callback1(() => {
  callback2(() => {
    callback3(() => {
      ...
    })
  })
});
```
비동기 처리가 이뤄진 후 어떤 동작을 하도록 해야하는 경우가 많다.  
예를 들어, 로그인과정을 살펴보자.  
1. ID와 Password를 서버와 통신해서 보냄. 통신 과정에서 비동기 동작.
2. 보낸 ID와 Password가 일치하면, 로그인 이후 창에 대한 데이터를 받음. 로그인 이후 창 받는 과정에서 비동기 동작. 
3. 로그인 이후 창을 성공적으로 받으면 해당 창을 띄움. 이 또한 비동기 동작.

이렇게 비동기 동작이 계속해서 쌓이는 경우가 발생할 수 있다.  
  
## callback 지옥을 해소하는 Promise의 chaining

```
//기존 방식

function job1() { ... return new promise(...) }
function job2() { ... return new promise(...) }

job1()
  .then(function(data){
    job2()
      .then(...)
```
똑같이 callback처럼 써버리면 이런식으로 다시 callback지옥을 떨어진다.  
하지만 promise는 chaining 방식으로 .then을 쓸 수 있다.
```
// chaining 방식

function job1() { ... return new promise(...) }
function job2() { ... return new promise(...) }


job1()
  .then(function(data){
    return job2();
  })
  .then(function(data){
    console.log('hello data');
  })
```

이렇게 .then 안에 함수의 return 값을 promise로 해버리면,  
계속해서 .then으로 이어나갈 수 있게된다.  

## chaining에서 에러 처리

```
job1()
  .then(function(data){
    return job2();
  })
  .then(function(data){
    console.log('hello data');
  })
  .catch( ... )
```

이런식으로 그냥 끝에 .catch() 해버리면 .then 어디에서 에러가 나더라도 전부 마지막에 .catch로 가서 에러를 실행한다.  
만약 .then마다 에러를 다르게 출력하고 싶다면  
```
job1()
  .then(function(data){
    return job2();
  })
  .catch( ... )
  .then(function(data){
    console.log('hello data');
  })
  .catch( ... )
```

이렇게 해도 된다.  
